---
# Install Kafka and dependencies
- name: Install Java (Prerequisite)
  dnf:
    name: java-11-amazon-corretto-devel
    state: present
  become: yes

- name: Download Kafka binaries
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    #url: "{{ kafka_url }}"
    dest: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    timeout: 60
  become: yes
  register: download_result

- name: Extract Kafka binaries
  ansible.builtin.unarchive:
    src: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/opt"
    remote_src: yes
    creates: "/opt/kafka_{{ scala_version }}-{{ kafka_version }}"
  become: yes

- name: Create a symlink to Kafka directory
  file:
    src: "/opt/kafka_{{ scala_version }}-{{ kafka_version }}"
    dest: /opt/kafka
    state: link
  become: yes

# Configure Kafka
- name: Deploy Kafka server properties
  ansible.builtin.template:
    src: ./templates/server.properties.j2
    dest: /opt/kafka/config/server.properties
  notify: reload kafka
  become: yes

# - name: Start Kafka Server in daemon mode
#   become: yes
#   notify: reload kafka
#   shell: /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties -daemon

- name: Start Kafka server as a daemon
  ansible.builtin.shell: |
    nohup /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties > /dev/null 2>&1 &
  async: 10
  poll: 0
  become: yes
